name: Generate routing rules for Surge
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "telegram_cidr=https://core.telegram.org/resources/cidr.txt" >> $GITHUB_ENV
          echo "Unbreak_list=https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Unbreak.list" >> $GITHUB_ENV
          echo "anti_ad_surge=https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge2.txt" >> $GITHUB_ENV
          echo "annoyances_filter=https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/annoyances-filter.txt" >> $GITHUB_ENV
          echo "base_filter=https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/base-filter.txt" >> $GITHUB_ENV
          echo "chinese_filter=https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/chinese-filter.txt" >> $GITHUB_ENV
          echo "social_media_filter=https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/social-media-filter.txt" >> $GITHUB_ENV
          echo "tracking_protection_filter=https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/tracking-protection-filter.txt" >> $GITHUB_ENV
          echo "adaway=https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/adaway.txt" >> $GITHUB_ENV
          echo "neohosts=https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/neohosts.txt" >> $GITHUB_ENV
          echo "Netflix=https://raw.githubusercontent.com/mangoclover/ios_rule_script/master/rule/Surge/Netflix/Netflix.list" >> $GITHUB_ENV
          echo "China=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/China/China.list" >> $GITHUB_ENV
        shell: bash
        
      - name: Checkout the default branch
        uses: actions/checkout@v2.3.4

      - name: Generate telegramcidr.txt file
        run: |
          mkdir -p Domainset
          mkdir -p Ruleset
          curl -sSL ${telegram_cidr} | perl -ne '/^(\d{1,3}(\.\d{1,3}){3}\/\d{1,2})/ && print "IP-CIDR,$1\n"' > Domainset/telegramcidr.txt
          curl -sSL ${telegram_cidr} | perl -ne '/^(\d{1,3}(\.\d{1,3}){3}\/\d{1,2})/ && print "IP-CIDR,$1\n"' > Ruleset/telegramcidr.list
          curl -sSL ${telegram_cidr} | grep ":" | perl -ne '/(.+\/\d+)/ && print "IP-CIDR6,$1\n"' >> Domainset/telegramcidr.txt
          curl -sSL ${telegram_cidr} | grep ":" | perl -ne '/(.+\/\d+)/ && print "IP-CIDR6,$1\n"' >> Ruleset/telegramcidr.list
          
      - name: Generate Unbreak_list file
        run: |
          curl -sSL ${Unbreak_list} > Ruleset/Unbreak.list
          
      - name: Generate anti-ad-surge file
        run: |
          curl -sSL ${anti_ad_surge}  | grep -v "#" > Domainset/anti-ad-surge.txt
          
      - name: Generate annoyances-filter file
        run: |
          curl -sSL ${annoyances_filter} > Domainset/annoyances-filter.txt
          
      - name: Generate base-filter file
        run: |
          curl -sSL ${base_filter} > Domainset/base-filter.txt
          
      - name: Generate chinese-filter file
        run: |
          curl -sSL ${chinese_filter} > Domainset/chinese-filter.txt
          
      - name: Generate social_media_filter file
        run: |
          curl -sSL ${social_media_filter} > Domainset/social-media-filter.txt
          
      - name: Generate tracking-protection-filter file
        run: |
          curl -sSL ${tracking_protection_filter} > Domainset/tracking-protection-filter.txt
          
      - name: Generate adaway file
        run: |
          curl -sSL ${adaway} > Domainset/adaway.txt
          
      - name: Generate neohosts file
        run: |
          curl -sSL ${neohosts} > Domainset/neohosts.txt
          
      - name: Generate Netflix file
        run: |
          curl -sSL ${Netflix}  | grep -v "#" > Ruleset/Netflix.list
          
      - name: Generate China file
        run: |
          curl -sSL ${China}  | grep -v "#" > Ruleset/China.list
     
      - name: Move files to publish directory
        run: |
          mkdir -p publish
          mv Ruleset ./publish/
          mv Domainset ./publish/
          
      - name: Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git push assets to "release" branch
        run: |
          cd publish
          git init
          git config --local user.name "github-action[bot]"
          git config --local user.email "48041092+mangoclover@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Purge CDN Cache
        run: |
          curl -L https://purge.jsdelivr.net/gh/mangoclover/Surge-Rules@release/Domainset/telegramcidr.txt > /dev/null 2>&1
          curl -L https://purge.jsdelivr.net/gh/mangoclover/Surge-Rules@release/Ruleset/telegramcidr.list > /dev/null 2>&1
          curl -L https://purge.jsdelivr.net/gh/mangoclover/Surge-Rules@release/Ruleset/Unbreak.list > /dev/null 2>&1
          curl -L https://purge.jsdelivr.net/gh/mangoclover/Surge-Rules@release/Domainset/anti-ad-surge.txt > /dev/null 2>&1
